services:
  portal:
    build:
      context: ./portal
      dockerfile: Dockerfile
    ports:
      - "43721:8080"
    environment:
      - DATABASE_URL=postgresql://ctf_user:ctf_password@db:5432/ctf_db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - ctf_network
    restart: unless-stopped

  challenges:
    build:
      context: ./challenges
      dockerfile: Dockerfile
    ports:
      - "43722:8000"
    environment:
      - DATABASE_URL=postgresql://ctf_user:ctf_password@db:5432/ctf_db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - ctf_network
    restart: unless-stopped

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=ctf_user
      - POSTGRES_PASSWORD=ctf_password
      - POSTGRES_DB=ctf_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ctf_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ctf_user -d ctf_db"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  ctf_network:
    driver: bridge

volumes:
  postgres_data: 